#!/bin/bash

# Генерируем requirements.txt
source .venv/bin/activate
pip freeze > requirements.txt

# Добавляем его в коммит (опционально)
git add requirements.txt
git commit -m "Update requirements.txt" || true  # Игнорируем ошибку, если изменений нет

# Продолжаем push
exit 0

