name: Deploy Flask App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            REPO_DIR="/root/sci-metric.git"
            FRONTEND_DIR="/root/sciencemetrics-front"
            BUILD_DIR="/root/Naukometria_Flask"
          
            cd /root || exit
          
            UPDATE_FRONTEND=0
          
            if [ ! -d "$REPO_DIR" ]; then
              git clone --mirror https://devops.fa.ru/crpo/sci-metric.git "$REPO_DIR"
              cd "$REPO_DIR"
              git remote add github https://github.com/Redegit/sciencemetrics-front.git
              UPDATE_FRONTEND=1
            else
              cd "$REPO_DIR"
              git remote update
          
              git fetch origin
              git fetch github
          
              DIFF=$(git diff refs/remotes/origin/dev refs/remotes/github/dev)
          
              if [ "$DIFF" ]; then
                UPDATE_FRONTEND=1
              fi
            fi
          
            if [ "$UPDATE_FRONTEND" = "1" ]; then
              echo "Changes detected, pushing and building frontend"
              git push --mirror github
          
              rm -rf "$FRONTEND_DIR"
              git clone https://github.com/Redegit/sciencemetrics-front.git "$FRONTEND_DIR"
              cd "$FRONTEND_DIR"
              git checkout dev
              npm ci
              npm run build
          
              rm -rf "$BUILD_DIR/dist"
              cp -r dist "$BUILD_DIR/"
            else

